#! /usr/bin/env node

/*
 * Room Automator
 * A simple API service for room automation via an arduino.
 *
 * Author: Jarred Kenny (jarredkenny@gmail.com)
 * Date  : January 6, 2015
 */

var arduino = require('./lib/arduino');
var server  = require('./lib/server');

server.get("/lights/toggle", function(req, res){
  arduino.lights.toggle();
  res.send();
});

server.get("/lights/off", function(req, res){
  arduino.lights.off();
  res.send();
});

server.get("/lights/on", function(){
  arduino.lights.on();
  res.send();
});

arduino.onReady(function(){
  server.start();
});
